# Generated by Django 4.1.5 on 2023-01-28 15:59

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_order_alter_product_description_shippingaddress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
       
    ]
